# Generated by Django 3.2.4 on 2021-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopalabras',
            name='audio',
        ),
        migrations.AddField(
            model_name='audiopalabras',
            name='audio',
            field=models.ManyToManyField(to='talk.Audio'),
        ),
    ]
