# Generated by Django 3.2.4 on 2021-06-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_auto_20210626_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioPalabras',
            new_name='AudioPalabra',
        ),
    ]
